workflows:
  build_google_play:
    name: Build for Google Play
    environment:
      flutter: stable
    scripts:
      - name: Build Google Play version
        script: |
          flutter build apk -t lib/main_google.dart
    artifacts:
      - build/app/outputs/flutter-apk/app-googlePlay-release.apk
    triggering:
      events:
        - tag
      tag_patterns:                 # Include or exclude watched tag labels
        - pattern: '*'
          include: true
