workflows:
  build_google_play:
    name: Build for Google Play
    environment:
      flutter: stable
    scripts:
      - name: Build Google Play version
        script: |
          flutter build apk -t lib/main_google.dart
      - name: Rename export file
        script: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-release-google-play.apk
      - name: Build main version
        script: |
          flutter build apk -t lib/main.dart
      - name: Rename export file
        script: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-release.apk
    artifacts:
      - build/app/outputs/flutter-apk/app-release-google-play.apk
      - build/app/outputs/flutter-apk/app-release.apk

    triggering:
      events:
        - tag
      tag_patterns:                 # Include or exclude watched tag labels
        - pattern: '*'
          include: true