name: Test

on:
  push:
    tags:
      - 't*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get version  
        id: read-version
        uses: NiklasLehnfeld/flutter-version-number-action@main
        with:
          file-path: pubspec.yaml
      - name: Print version
        run: "echo Version: ${{ steps.read-version.outputs.version-number }}"

      - name: Get the tag and remove the first character
        id: get_tag
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          TAG_WITHOUT_FIRST_CHAR=${TAG:1}
          echo "TAG_WITHOUT_FIRST_CHAR=$TAG_WITHOUT_FIRST_CHAR" >> $GITHUB_ENV

      - uses: nick-invision/assert-action@v1
        with:
          expected: ${{ env.TAG_WITHOUT_FIRST_CHAR }}
          actual: ${{ steps.read-version.outputs.version-number }}
      
      # - name: Get version
      #   id: yq
      #   uses: mikefarah/yq@master
      #   with:
      #     cmd: yq -r .version pubspec.yaml

      # - name: Get Project Version
      #   run: echo "v${{ steps.yq.outputs }}"
        # run: echo "::set-output name=project_version::$(echo ${{ steps.yq.outputs.version }})"
